### ISSUE TITLE
 {'errors': [{'code': 326, 'message': 'To protect our users from spam and other malicious activity, this account is temporarily locked. Please log in to https://twitter.com to unlock your account.', 'sub_error_code': 0, 'bounce_location': 'https://twitter.com/account/access'}]}

### ISSUE THREAD

**Issue by mtrsu4484** [Twitter-Tools/TwitterAccountGenerator#5] opened 2024-04-07 16:18 UTC
i used this script  try to creat accounts, all of them return 326 code. 

any suggestion?

**Comment by phinwww** [comment] 2024-04-07 16:21
https://github.com/Twitter-Tools/TwitterTokensUnlocker

**Comment by aa552882** [comment] 2024-04-07 16:22
duplicate of #1

**Comment by mtrsu4484** [comment] 2024-04-07 16:26
thank you @phinwww how can i save the locked token? and the username&email?

**Comment by mtrsu4484** [comment] 2024-04-07 16:43
solved, thank you

**Closed** 2024-04-07 16:49 UTC
